[package]
name = "orml-traits"
version = "0.0.1"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sp-runtime = { version = "2.0.0-alpha.3", default-features = false }
runtime-io = { package = "sp-io", version = "2.0.0-alpha.3", default-features = false }
rstd = { package = "sp-std", version = "2.0.0-alpha.3", default-features = false }
num-traits = { version = "0.2.8", default-features = false }
impl-trait-for-tuples = "0.1.3"

[dev-dependencies]
clear_on_drop = { version = "0.2.3", features = ["no_cc"] }	# https://github.com/paritytech/substrate/issues/4179

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"runtime-io/std",
	"rstd/std",
	"num-traits/std",
]
