[package]
name = "orml-traits"
version = "0.0.1"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate.git", default-features = false }
runtime_io = { package = "sr-io", git = "https://github.com/paritytech/substrate.git", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate.git", default-features = false }
num-traits = { version = "0.2.8", default-features = false }
impl-trait-for-tuples = "0.1.3"

palette_support = { package = "palette-support", git = "https://github.com/paritytech/substrate.git" }
palette_system = { package = "palette-system", git = "https://github.com/paritytech/substrate.git" }
substrate-runtime-interface = { git = "https://github.com/paritytech/substrate.git", features = ['disable_target_static_assertions'] }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sr-primitives/std",
	"runtime_io/std",
	"rstd/std",
	"num-traits/std",
	"palette_support/std",
	"palette_system/std",
]
